jobs:
  include:
  - Name: "Http Server"
    jdk: oraclejdk11
    language: java
    script:
    - "./gradlew build && ./gradlew test"
  - Name: "Http Server Spec (Spinach)"
    rvm: 2.5.5
    install:
    - git clone git@github.com:Naomi-Dennis/http_server_spec.git
    - cd http_server_spec
    script:
    - bundle install
    - bundle exec spinach
  allow_failures:
    - rvm: 2.5.5

before_install:
- openssl aes-256-cbc -K $encrypted_9e535d2dfa01_key -iv $encrypted_9e535d2dfa01_iv
  -in github_deploy_key.enc -out github_deploy_key -d
- chmod 400 github_deploy_key
- eval "$(ssh-agent -s)"
- ssh-add -t 10 github_deploy_key
