version: 0.0
os: linux
files:
  - source: EchoService.jar
    destination: /opt
  - source: SimpleApplication.jar
    destination: /opt
  - source: deploy_server.sh
    destination: /opt
hooks:
  ApplicationStart:
  - location: deploy_server.sh
